// Ported constants from the backend mastering chain (upmixer/mastering/*.py) and
// stem router (upmixer/separation/stem_router.py) so the preview's Web Audio graph
// can approximate the same tone/dynamics/loudness shaping as the delivered mix.
// Keep these numbers in sync with the Python source — they are not derived at runtime.

export type EqProfileName =
  | "spatial-transparent"
  | "spatial-air"
  | "spatial-warm"
  | "spatial-present"
  | "atmos-streaming";

// Maps each mastering-bus EQ profile to its precomputed FIR asset filename
// (without extension) under `/eq_fir/`. The WAV is the *actual* minimum-phase
// FIR upmixer/mastering/eq.py's `_build_fir` computes at runtime (48kHz,
// 1023 taps) — generated by scripts/build_eq_filters.py, which calls that
// exact function, so the preview convolves against the real backend impulse
// response (via `buildFirEqNode`) instead of approximating the curve with
// biquad filters. See that script's docstring for provenance.
export const EQ_FIR_ASSETS: Record<EqProfileName, string> = {
  "spatial-transparent": "master_spatial-transparent",
  "spatial-air": "master_spatial-air",
  "spatial-warm": "master_spatial-warm",
  "spatial-present": "master_spatial-present",
  "atmos-streaming": "master_atmos-streaming",
};

export type StemEqProfileName =
  | "vocal-presence"
  | "vocal-warmth"
  | "bass-warmth"
  | "bass-cut"
  | "drums-punch"
  | "other-air"
  | "flat";

// Same asset scheme as EQ_FIR_ASSETS above, for upmixer/separation/stem_eq.py's
// per-stem profiles (48kHz, 511 taps) — applied before spatial routing,
// unlike EQ_FIR_ASSETS which shapes the post-routing mastering bus.
export const STEM_EQ_FIR_ASSETS: Record<StemEqProfileName, string> = {
  "vocal-presence": "stem_vocal-presence",
  "vocal-warmth": "stem_vocal-warmth",
  "bass-warmth": "stem_bass-warmth",
  "bass-cut": "stem_bass-cut",
  "drums-punch": "stem_drums-punch",
  "other-air": "stem_other-air",
  flat: "stem_flat",
};

export type CompProfileName = "transparent" | "glue" | "warm";

export type CompProfile = {
  threshold_db: number;
  ratio: number;
  attack_ms: number;
  release_ms: number;
  knee_db: number;
  makeup_db: number;
};

// upmixer/mastering/compressor.py COMP_PROFILES.
export const COMP_PROFILES: Record<CompProfileName, CompProfile> = {
  transparent: { threshold_db: -22.0, ratio: 1.5, attack_ms: 30.0, release_ms: 300.0, knee_db: 9.0, makeup_db: 0.0 },
  glue: { threshold_db: -18.0, ratio: 2.0, attack_ms: 20.0, release_ms: 200.0, knee_db: 6.0, makeup_db: 0.0 },
  warm: { threshold_db: -15.0, ratio: 2.0, attack_ms: 40.0, release_ms: 400.0, knee_db: 12.0, makeup_db: 0.0 },
};

export type BassProfileName = "boost" | "cut" | "mono" | "enhance";

export type BassProfile = {
  sub_gain_db: number;
  mid_gain_db: number;
  mono_cutoff_hz: number | null;
  excite: boolean;
  lfe_gain_db: number;
};

// upmixer/mastering/bass.py BASS_PROFILES.
export const BASS_PROFILES: Record<BassProfileName, BassProfile> = {
  boost: { sub_gain_db: 2.0, mid_gain_db: 1.0, mono_cutoff_hz: null, excite: false, lfe_gain_db: 1.5 },
  cut: { sub_gain_db: -2.5, mid_gain_db: -1.5, mono_cutoff_hz: null, excite: false, lfe_gain_db: -1.0 },
  mono: { sub_gain_db: 0.0, mid_gain_db: 0.0, mono_cutoff_hz: 100.0, excite: false, lfe_gain_db: 0.0 },
  enhance: { sub_gain_db: 1.5, mid_gain_db: 0.5, mono_cutoff_hz: 80.0, excite: true, lfe_gain_db: 1.0 },
};

export const SUB_CUTOFF_HZ = 80.0;
export const MID_CUTOFF_HZ = 200.0;
export const EXCITE_BLEND = 0.15;
export const EXCITE_DRIVE = 3.0;

// scipy.signal.butter's default Q for a 2nd-order Butterworth section.
// Web Audio's BiquadFilterNode lowpass/highpass default Q=1 has a small
// resonant peak (about +1dB near cutoff) a true Butterworth response
// doesn't — set explicitly on any biquad standing in for a
// `butter(2, ..., output="sos")` backend filter (bass mono-maker,
// surround/height sends) so passband/stopband energy near the cutoff
// tracks the backend more closely. Found via
// docs/contracts/preview_export_parity.md's golden-diff harness: without
// this, the bass mono-maker leaked enough extra energy near its cutoff to
// flip its net level effect from a slight cut (backend) to a slight boost
// (preview) on decorrelated multichannel content — see Ledger D9.
export const BUTTERWORTH_Q = 1 / Math.sqrt(2);

// upmixer/mastering/bass.py STEREO_PAIRS — bass mono-maker operates on these
// L/R channel pairs (see `useStemPreview.ts`'s `buildMasteringTopology`).
export const MONO_MAKER_STEREO_PAIRS: ReadonlyArray<readonly [string, string]> = [
  ["FL", "FR"],
  ["SL", "SR"],
  ["BL", "BR"],
  ["TFL", "TFR"],
  ["TBL", "TBR"],
];

// upmixer/config.py peak_limit_threshold — not manifest-editable, fixed default.
export const SOFT_LIMIT_THRESHOLD = 0.95;

// upmixer/config.py lfe_gain (-10 dB) and stem_router LFE lowpass.
export const LFE_GAIN = 0.31622776601683794;
export const LFE_LOWPASS_HZ = 120;

// upmixer/config.py loudness_max_gain_db.
export const LOUDNESS_MAX_GAIN_DB = 30.0;

// upmixer/utils.py _ITU_C_COEFF (1/sqrt(2), exact) — the fixed center-channel
// downmix coefficient ITU-R BS.775-4 Annex 4 Table 2 uses for the C-term and
// the back->side fold, distinct from the user-configurable surround
// coefficient below even though they default to (nearly) the same number.
export const ITU_CENTER_COEFF = 1 / Math.sqrt(2);

// upmixer/config.py surround_downmix_coeff default. User-configurable via
// format.downmix.surround_coeff (see manifest.ts); 0.7071 is a truncated
// approximation of 1/sqrt(2), not the exact value — matching the backend's
// own truncated default exactly, not a rounding error to "fix".
export const SURROUND_DOWNMIX_COEFF = 0.7071;

// upmixer/binaural/renderer.py BINAURAL_LOUDNESS_MAX_GAIN_DB. The bed is
// already loudness-normalized before binaural collapse, so this pass only
// lightly corrects for the level shift the HOA/HRTF collapse introduces
// instead of re-running a full loudness match — a small ceiling keeps a
// quiet collapse from being cranked back up past the mastered bed's level.
export const BINAURAL_LOUDNESS_MAX_GAIN_DB = 6.0;

/** WaveShaper curve for the backend's tanh soft-limit: identity below
 * `threshold`, tanh saturation above it. Mirrors upmixer/utils.py soft_limit. */
export function buildSoftLimitCurve(threshold: number = SOFT_LIMIT_THRESHOLD, samples = 4096): Float32Array {
  const curve = new Float32Array(samples);
  const margin = 1.0 - threshold;
  for (let i = 0; i < samples; i++) {
    const x = (i / (samples - 1)) * 2 - 1;
    const ax = Math.abs(x);
    curve[i] = ax <= threshold
      ? x
      : Math.sign(x) * (threshold + margin * Math.tanh((ax - threshold) / margin));
  }
  return curve;
}

/** WaveShaper curve for the bass exciter: tanh(x * drive). Mirrors the
 * harmonic-exciter stage in upmixer/mastering/bass.py. */
export function buildExciteCurve(drive: number = EXCITE_DRIVE, samples = 4096): Float32Array {
  const curve = new Float32Array(samples);
  for (let i = 0; i < samples; i++) {
    const x = (i / (samples - 1)) * 2 - 1;
    curve[i] = Math.tanh(x * drive);
  }
  return curve;
}

/** Fetches and decodes an EQ FIR asset (see `EQ_FIR_ASSETS`/`STEM_EQ_FIR_ASSETS`)
 * from `/eq_fir/<assetName>.wav`. Callers should cache the returned promise
 * per `assetName` (see `useStemPreview.ts`'s buffer cache) — the same
 * profile is commonly reused across many stems or across a rebuild. */
export async function fetchEqFirBuffer(ctx: BaseAudioContext, assetName: string): Promise<AudioBuffer> {
  const response = await fetch(`/eq_fir/${assetName}.wav`);
  if (!response.ok) throw new Error(`EQ FIR asset missing: ${assetName}.wav`);
  const data = await response.arrayBuffer();
  return ctx.decodeAudioData(data);
}

export type FirEqNode = {
  input: AudioNode;
  output: AudioNode;
  convolver: ConvolverNode;
  dryGain: GainNode;
  wetGain: GainNode;
  nodes: AudioNode[];
};

/** Builds a wet/dry FIR EQ insert: `input` splits into a dry passthrough and
 * a `ConvolverNode` (bank-summed the same way the backend's `_apply_fir`
 * blends `(1-strength)*dry + strength*filtered`), recombining at `output`.
 * The convolver's `buffer` starts unset (silent wet path, per the Web Audio
 * spec) — non-blocking, matching the binaural decode bank's loading
 * pattern: callers wire this synchronously into the graph, then assign
 * `convolver.buffer` once `fetchEqFirBuffer` resolves, so playback can start
 * immediately while the FIR asset is still fetching/decoding. Callers that
 * rebuild their whole topology on any mastering-config change (as
 * `buildMasteringTopology`/`buildStemEqChains` do) just build a fresh node
 * at the new `strength` rather than retuning an existing one. */
export function buildFirEqNode(ctx: BaseAudioContext, strength: number): FirEqNode {
  const input = ctx.createGain();
  const convolver = ctx.createConvolver();
  convolver.normalize = false;
  const dryGain = ctx.createGain();
  const wetGain = ctx.createGain();
  const output = ctx.createGain();
  input.connect(dryGain).connect(output);
  input.connect(convolver).connect(wetGain).connect(output);
  dryGain.gain.value = 1 - strength;
  wetGain.gain.value = strength;
  return { input, output, convolver, dryGain, wetGain, nodes: [input, convolver, dryGain, wetGain, output] };
}

/** Connect `start -> nodes[0] -> nodes[1] -> ... -> nodes[n-1]` in series and
 * return the last node in the chain (or `start` when `nodes` is empty). */
export function connectSeries(start: AudioNode, nodes: AudioNode[]): AudioNode {
  let previous = start;
  for (const node of nodes) {
    previous.connect(node);
    previous = node;
  }
  return previous;
}

// --- Channel-bed router (ported from upmixer/separation/stem_router.py) --
//
// The preview used to binauralize each stem as a point object via a Web
// Audio HRTF PannerNode — that convolves every source with one generic,
// non-personalized HRIR with a diffuse-field high-frequency rolloff, so
// HRTF-panned sources read as duller than the dry final master (worse than
// a single EQ shelf could fix), and the API exposes no way to load a
// different HRTF. An earlier fix layered a fixed compensation EQ on the
// HRTF bus and hard-switched some sources to a dry stereo pan to dodge the
// comb filtering an undelayed dry copy causes against the panner's
// unqueryable ITD — both hacks are gone now.
//
// The preview now mirrors the backend exactly: stems are routed into the
// same 11-speaker channel bed `StemRouter.route` builds (this file's
// constants below), and *that* channel bed — not the individual stems — is
// what gets encoded to ambisonics and binauralized (see useStemPreview.ts).
// This is the "virtual loudspeaker" rendering model (each output channel is
// a fixed ambisonic point source), the same approach Apple's Spatial Audio
// renderer uses, and it lets a user mute a speaker as well as a stem.

/** Per-channel-group gains — upmixer/config.py `center_gain`/`surround_gain`/
 * `back_gain`/`height_gain`. FL/FR always 1.0 (no group). */
export const CENTER_GAIN = 0.85;
export const SURROUND_GAIN = 0.6;
export const BACK_GAIN = 0.55;
export const HEIGHT_GAIN = 0.55;

export function channelGroupGain(channel: string): number {
  if (channel === "C") return CENTER_GAIN;
  if (channel === "BL" || channel === "BR") return BACK_GAIN;
  if (channel === "SL" || channel === "SR") return SURROUND_GAIN;
  if (channel === "TFL" || channel === "TFR" || channel === "TBL" || channel === "TBR") return HEIGHT_GAIN;
  return 1.0;
}

/** upmixer/config.py `surround_bass_cutoff_hz` — highpass applied to a
 * stem's surround/back send before its Haas decorrelation delay. */
export const SURROUND_BASS_CUTOFF_HZ = 250.0;

/** upmixer/config.py height-send shaping (`_height_send` in
 * stem_router.py, same formula as `upmixer/utils.py` `elevation_eq`):
 * attenuate below `HEIGHT_LOW_ROLLOFF_HZ` to `HEIGHT_LOW_ROLLOFF_GAIN`,
 * then boost above `HEIGHT_CROSSOVER_HZ` by `HEIGHT_HIGH_SHELF_GAIN`. */
export const HEIGHT_LOW_ROLLOFF_HZ = 150.0;
export const HEIGHT_LOW_ROLLOFF_GAIN = 0.15;
export const HEIGHT_CROSSOVER_HZ = 3000.0;
export const HEIGHT_HIGH_SHELF_GAIN = 1.5;

/** upmixer/utils.py `diffuse_send` default wet blend. */
export const DIFFUSE_SEND_BLEND = 0.55;

/** stem_router.py `route()` — per-side Haas delays (ms) for surround/back
 * and height sends. Different per side so L/R don't comb-filter. */
export const SURROUND_HAAS_MS = { left: 31, right: 37 };
export const HEIGHT_HAAS_MS = { left: 23, right: 29 };

/** Web Audio version of `upmixer/utils.py` `diffuse_send`: blends a signal
 * with a delayed copy of itself for early-reflection decorrelation. */
export function buildDiffuseSend(
  ctx: AudioContext,
  input: AudioNode,
  delayMs: number,
  blend: number = DIFFUSE_SEND_BLEND,
): { output: AudioNode; nodes: AudioNode[] } {
  const delay = ctx.createDelay(1);
  delay.delayTime.value = delayMs / 1000;
  const dry = ctx.createGain();
  dry.gain.value = 1 - blend;
  const wet = ctx.createGain();
  wet.gain.value = blend;
  const output = ctx.createGain();
  input.connect(dry).connect(output);
  input.connect(delay).connect(wet).connect(output);
  return { output, nodes: [delay, dry, wet, output] };
}

/** Web Audio version of `stem_router.py` `_height_send` /
 * `upmixer/utils.py` `elevation_eq`: sub-bass rolloff (kept at
 * `HEIGHT_LOW_ROLLOFF_GAIN`, not fully removed) plus a top-end shelf boost
 * above the crossover. Implemented as the additive identity the Python
 * `sosfilt` version reduces to: `shaped = x - low·(1-g); out = shaped +
 * high(shaped)·(shelfGain-1)`. */
export function buildHeightSend(ctx: AudioContext, input: AudioNode): { output: AudioNode; nodes: AudioNode[] } {
  const lowpass = ctx.createBiquadFilter();
  lowpass.type = "lowpass";
  lowpass.frequency.value = HEIGHT_LOW_ROLLOFF_HZ;
  const lowComp = ctx.createGain();
  lowComp.gain.value = -(1 - HEIGHT_LOW_ROLLOFF_GAIN);
  const shaped = ctx.createGain();
  input.connect(shaped);
  input.connect(lowpass).connect(lowComp).connect(shaped);

  const highpass = ctx.createBiquadFilter();
  highpass.type = "highpass";
  highpass.frequency.value = HEIGHT_CROSSOVER_HZ;
  highpass.Q.value = BUTTERWORTH_Q;
  const highGain = ctx.createGain();
  highGain.gain.value = HEIGHT_HIGH_SHELF_GAIN - 1;
  const output = ctx.createGain();
  shaped.connect(output);
  shaped.connect(highpass).connect(highGain).connect(output);

  return { output, nodes: [lowpass, lowComp, shaped, highpass, highGain, output] };
}

/** Web Audio version of `stem_router.py`'s surround send: a highpass at
 * `SURROUND_BASS_CUTOFF_HZ` (keeps rhythmic low end out of the diffuse
 * surround/back layer) followed by the Haas diffuse send. */
export function buildSurroundSend(
  ctx: AudioContext,
  input: AudioNode,
  delayMs: number,
): { output: AudioNode; nodes: AudioNode[] } {
  const highpass = ctx.createBiquadFilter();
  highpass.type = "highpass";
  highpass.frequency.value = SURROUND_BASS_CUTOFF_HZ;
  highpass.Q.value = BUTTERWORTH_Q;
  input.connect(highpass);
  const diffuse = buildDiffuseSend(ctx, highpass, delayMs);
  return { output: diffuse.output, nodes: [highpass, ...diffuse.nodes] };
}

// --- Spatial Audio Engine voicing chain (ported from upmixer/binaural/) --
//
// Studio/Listening/Flat binaural profiles. Filter geometry/SH/decode-filter
// contract lives in docs/standards/spatial_audio_engine.md; this section
// only carries the post-decode "voicing" parameters (Listening's
// Apple-Music-style enhance chain) so useStemPreview.ts's Web Audio graph
// can match upmixer/binaural/voicing.py parameter-for-parameter.

export type SpatialProfile = "studio" | "listening" | "flat";

export const DECODE_FILTER_SET: Record<SpatialProfile, string> = {
  flat: "flat_o3_decode",
  studio: "studio_o3_decode",
  listening: "listening_o3_decode",
};

export type VoicingParams = {
  crossfeedAmount: number;
  crossfeedCutoffHz: number;
  bassShelfHz: number;
  bassShelfGainDb: number;
  airShelfHz: number;
  airShelfGainDb: number;
  presenceHz: number;
  presenceGainDb: number;
  presenceQ: number;
  stereoWiden: number;
  loudnessTargetLkfs: number | null;
};

const NEUTRAL_VOICING: VoicingParams = {
  crossfeedAmount: 0, crossfeedCutoffHz: 700, bassShelfHz: 120, bassShelfGainDb: 0,
  airShelfHz: 9000, airShelfGainDb: 0, presenceHz: 3000, presenceGainDb: 0, presenceQ: 0.9,
  stereoWiden: 0, loudnessTargetLkfs: null,
};

// upmixer/binaural/profiles.py VOICING_PARAMS.
export const VOICING_PARAMS: Record<SpatialProfile, VoicingParams> = {
  flat: NEUTRAL_VOICING,
  studio: NEUTRAL_VOICING,
  listening: {
    crossfeedAmount: 0.28, crossfeedCutoffHz: 700,
    bassShelfHz: 120, bassShelfGainDb: 1.0,
    airShelfHz: 9000, airShelfGainDb: 1.0,
    presenceHz: 3000, presenceGainDb: 0.5, presenceQ: 0.9,
    stereoWiden: 0.10, loudnessTargetLkfs: -16.0,
  },
};

// Ambisonic order for the virtual-loudspeaker renderer shared by the live
// preview (useStemPreview.ts) and the golden-diff harness's extracted
// buildBinauralGraph below — see docs/standards/spatial_audio_engine.md.
// Higher order = tighter localization, more encoder channels ((order+1)^2).
export const AMBISONIC_ORDER = 3;
export const N_ACN_CHANNELS = (AMBISONIC_ORDER + 1) * (AMBISONIC_ORDER + 1);

// upmixer/binaural/ambisonics.py::encode_gains's ACN 12 (Y3^0, the order-3
// vertical harmonic) omits the standard N3D sqrt(7) normalization factor. The
// decode filter bank (docs/standards/spatial_audio_engine.md §4) was fit as
// the pseudo-inverse of that unscaled encoder, so this preview's
// standard-N3D real-SH encoder output for ACN 12 must be scaled down to
// match what the filters were designed against. See that doc's §3.
export const ACN12_INDEX = 12;
export const ACN12_N3D_CORRECTION = 1 / Math.sqrt(7);

// Decode filter set contract (docs/standards/spatial_audio_engine.md §4):
// 16 ACN channels x {L, R} FIR filters, shipped as four 8-channel WAVs so
// the browser's per-file multichannel decode stays under its 8ch cap.
export const DECODE_FILTER_SPLITS = ["01-08ch", "09-16ch", "17-24ch", "25-32ch"] as const;

export type VoicingChain = {
  left: AudioNode;
  right: AudioNode;
  nodes: AudioNode[];
  lowL: BiquadFilterNode;
  lowR: BiquadFilterNode;
  dryL: GainNode;
  dryR: GainNode;
  bleedToL: GainNode;
  bleedToR: GainNode;
  bassL: BiquadFilterNode;
  bassR: BiquadFilterNode;
  airL: BiquadFilterNode;
  airR: BiquadFilterNode;
  presenceL: BiquadFilterNode;
  presenceR: BiquadFilterNode;
  sideL: GainNode;
  sideR: GainNode;
};

/** Web Audio voicing chain: crossfeed -> bass/air shelves -> presence peak
 * -> M/S widen. Mirrors upmixer/binaural/voicing.py::apply_voicing exactly
 * (same order, same parameters). Builds a fixed topology regardless of
 * profile — a zero-gain shelf/peak or zero-amount crossfeed/widen stage is
 * already numerically an identity, so switching profiles only needs
 * `applyVoicingParams` to retune existing AudioParams, never a graph
 * rebuild. Returns the two output nodes to connect onward (left, right),
 * every node created (for teardown), and the tunable nodes themselves. */
export function buildVoicingChain(ctx: BaseAudioContext, left: AudioNode, right: AudioNode): VoicingChain {
  const lowL = ctx.createBiquadFilter();
  lowL.type = "lowpass";
  const lowR = ctx.createBiquadFilter();
  lowR.type = "lowpass";
  left.connect(lowL);
  right.connect(lowR);

  const dryL = ctx.createGain();
  const dryR = ctx.createGain();
  const bleedToL = ctx.createGain();
  const bleedToR = ctx.createGain();
  const crossfedL = ctx.createGain();
  const crossfedR = ctx.createGain();
  left.connect(dryL).connect(crossfedL);
  lowR.connect(bleedToL).connect(crossfedL);
  right.connect(dryR).connect(crossfedR);
  lowL.connect(bleedToR).connect(crossfedR);

  const bassL = ctx.createBiquadFilter();
  bassL.type = "lowshelf";
  const bassR = ctx.createBiquadFilter();
  bassR.type = "lowshelf";
  const airL = ctx.createBiquadFilter();
  airL.type = "highshelf";
  const airR = ctx.createBiquadFilter();
  airR.type = "highshelf";
  const presenceL = ctx.createBiquadFilter();
  presenceL.type = "peaking";
  const presenceR = ctx.createBiquadFilter();
  presenceR.type = "peaking";
  crossfedL.connect(bassL).connect(airL).connect(presenceL);
  crossfedR.connect(bassR).connect(airR).connect(presenceR);

  // M/S widen: mid = (L+R)/2, side = (L-R) * (1+w)/2; out = mid +- side.
  // `side` carries the true L-R difference (presenceR negated via
  // `sideDiff`) so both sideL and sideR scale the *same* difference signal —
  // tapping presenceL/presenceR directly here would make sideL/sideR each
  // pass a single raw channel instead of a true side signal, so even
  // `stereoWiden = 0` would fail to reduce to identity.
  const mid = ctx.createGain();
  mid.gain.value = 0.5;
  const side = ctx.createGain();
  const sideDiff = ctx.createGain();
  sideDiff.gain.value = -1;
  const sideL = ctx.createGain();
  const sideR = ctx.createGain();
  presenceL.connect(mid);
  presenceR.connect(mid);
  presenceL.connect(side);
  presenceR.connect(sideDiff).connect(side);
  side.connect(sideL);
  side.connect(sideR);

  const outL = ctx.createGain();
  const outR = ctx.createGain();
  mid.connect(outL);
  sideL.connect(outL);
  mid.connect(outR);
  sideR.connect(outR);

  return {
    left: outL,
    right: outR,
    nodes: [
      lowL, lowR, dryL, dryR, bleedToL, bleedToR, crossfedL, crossfedR,
      bassL, bassR, airL, airR, presenceL, presenceR,
      mid, side, sideDiff, sideL, sideR, outL, outR,
    ],
    lowL, lowR, dryL, dryR, bleedToL, bleedToR,
    bassL, bassR, airL, airR, presenceL, presenceR, sideL, sideR,
  };
}

/** Retunes an existing `VoicingChain`'s AudioParams for a new profile — no
 * node creation, so it's safe to call on every profile switch or animate. */
export function applyVoicingParams(chain: VoicingChain, params: VoicingParams): void {
  chain.lowL.frequency.value = params.crossfeedCutoffHz;
  chain.lowR.frequency.value = params.crossfeedCutoffHz;
  chain.dryL.gain.value = 1 - params.crossfeedAmount;
  chain.dryR.gain.value = 1 - params.crossfeedAmount;
  chain.bleedToL.gain.value = params.crossfeedAmount;
  chain.bleedToR.gain.value = params.crossfeedAmount;
  chain.bassL.frequency.value = params.bassShelfHz;
  chain.bassR.frequency.value = params.bassShelfHz;
  chain.bassL.gain.value = params.bassShelfGainDb;
  chain.bassR.gain.value = params.bassShelfGainDb;
  chain.airL.frequency.value = params.airShelfHz;
  chain.airR.frequency.value = params.airShelfHz;
  chain.airL.gain.value = params.airShelfGainDb;
  chain.airR.gain.value = params.airShelfGainDb;
  chain.presenceL.frequency.value = params.presenceHz;
  chain.presenceR.frequency.value = params.presenceHz;
  chain.presenceL.Q.value = params.presenceQ;
  chain.presenceR.Q.value = params.presenceQ;
  chain.presenceL.gain.value = params.presenceGainDb;
  chain.presenceR.gain.value = params.presenceGainDb;
  chain.sideL.gain.value = 0.5 * (1 + params.stereoWiden);
  chain.sideR.gain.value = -0.5 * (1 + params.stereoWiden);
}

/** Approximates `stem_router.py`'s per-stem constant-power `route_scale`
 * (`sqrt(input_energy/routed_energy)`) from the route table alone, treating
 * every contributing send as comparable energy — good enough to keep a
 * widely-routed stem from reading louder than a narrowly-routed one, not an
 * exact energy match (the real value needs the decoded buffers' energy). */
export function estimateRouteScale(route: Record<string, number>): number {
  let sumSquares = 0;
  for (const [channel, weight] of Object.entries(route)) {
    if (channel === "LFE" || weight <= 0) continue;
    const scaled = weight * channelGroupGain(channel);
    sumSquares += scaled * scaled;
  }
  return sumSquares > 1e-10 ? 1 / Math.sqrt(sumSquares) : 1;
}
