// Test-only fixture: a full `constants` payload matching what the backend
// `engine_constants()` serves, using the same values the engine formerly
// hardcoded. Imported by web tests that build a `Configuration` or drive the
// preview engine — NOT by app code (the real values arrive from
// GET /api/v1/configuration at runtime). This is a fixture, not a parity
// source: the authoritative values live in packages/core.
import { resolveEngineConstants, type ServedEngineConstants, type ServedVoicingParams } from "./masteringProfiles";

const neutral: ServedVoicingParams = {
  crossfeed_amount: 0,
  crossfeed_cutoff_hz: 700,
  bass_shelf_hz: 120,
  bass_shelf_gain_db: 0,
  air_shelf_hz: 9000,
  air_shelf_gain_db: 0,
  presence_hz: 3000,
  presence_gain_db: 0,
  presence_q: 0.9,
  stereo_widen: 0,
  loudness_target_lkfs: null,
};

export const TEST_SERVED_CONSTANTS: ServedEngineConstants = {
  channel_group_gains: { center: 0.85, surround: 0.6, back: 0.55, height: 0.55 },
  lfe_gain: 0.31622776601683794,
  lfe_lowpass_hz: 120,
  lfe_filter_order: 4,
  surround_bass_cutoff_hz: 250,
  height_low_rolloff_hz: 150,
  height_low_rolloff_gain: 0.15,
  height_crossover_hz: 3000,
  height_directional_band_hz: 8000,
  height_directional_band_gain: 1,
  height_high_shelf_gain: 1.5,
  soft_limit_threshold: 0.95,
  limiter_lookahead_ms: 5.0,
  limiter_release_ms: 50.0,
  safety_margin_db: 0.1,
  loudness_max_gain_db: 30.0,
  surround_downmix_coeff: 0.7071,
  height_downmix_coeff: 0.7071,
  speaker_directions: {
    FL: { azimuth_rad: 0.5216182970963865, elevation_rad: 0.0 },
    FR: { azimuth_rad: -0.5216182970963865, elevation_rad: 0.0 },
    C: { azimuth_rad: -0.0, elevation_rad: 0.0 },
    SL: { azimuth_rad: 1.9178579303343872, elevation_rad: 0.0 },
    SR: { azimuth_rad: -1.9178579303343872, elevation_rad: 0.0 },
    BL: { azimuth_rad: 2.356194490192345, elevation_rad: 0.0 },
    BR: { azimuth_rad: -2.356194490192345, elevation_rad: 0.0 },
    TFL: { azimuth_rad: 0.6202494859828215, elevation_rad: 0.6090366098458619 },
    TFR: { azimuth_rad: -0.6202494859828215, elevation_rad: 0.6090366098458619 },
    TBL: { azimuth_rad: 2.356194490192345, elevation_rad: 0.6154797086703874 },
    TBR: { azimuth_rad: -2.356194490192345, elevation_rad: 0.6154797086703874 },
  },
  dyneq_profiles: {
    "tame-harshness": [
      { freq_hz: 3500, q: 1.8, threshold_db: -32, ratio: 3, attack_ms: 15, release_ms: 180 },
    ],
  },
  stem_dynamic_eq_profiles: {
    "vocal-sibilance": [{ enabled: true, freq_hz: 7500, q: 3, threshold_db: -31, ratio: 4, max_cut_db: 6, attack_ms: 2, release_ms: 80 }],
  },
  stem_dynamics_profiles: {
    "vocal-control": { enabled: false, profile: null, threshold_db: -20, ratio: 1.8, attack_ms: 15, release_ms: 180, mix: 100 },
  },
  stem_processing_presets: {
    eq: { Vocals: ["vocal-presence"] },
    dynamic_eq: { Vocals: ["vocal-sibilance"] },
    dynamics: { Vocals: ["vocal-control"] },
  },
  reference_match_smooth: { default_oct: 1 / 3, min_oct: 1 / 12, max_oct: 1 },
  comp_profiles: {
    transparent: { threshold_db: -22.0, ratio: 1.5, attack_ms: 30.0, release_ms: 300.0, knee_db: 9.0, makeup_db: 0.0, sidechain_hpf_hz: null },
    glue: { threshold_db: -18.0, ratio: 2.0, attack_ms: 20.0, release_ms: 200.0, knee_db: 6.0, makeup_db: 0.0, sidechain_hpf_hz: null },
    warm: { threshold_db: -15.0, ratio: 2.0, attack_ms: 40.0, release_ms: 400.0, knee_db: 12.0, makeup_db: 0.0, sidechain_hpf_hz: null },
  },
  bass_profiles: {
    boost: { sub_gain_db: 2.0, mid_gain_db: 1.0, unify_hz: null, spread: "bed", punch: 0.0, excite: false, lfe_mode: "off", lfe_send: 0.0, lfe_gain_db: 1.5, decorrelate: 0.0 },
    cut: { sub_gain_db: -2.5, mid_gain_db: -1.5, unify_hz: null, spread: "bed", punch: 0.0, excite: false, lfe_mode: "off", lfe_send: 0.0, lfe_gain_db: -1.0, decorrelate: 0.0 },
    mono: { sub_gain_db: 0.0, mid_gain_db: 0.0, unify_hz: 90.0, spread: "front", punch: 0.0, excite: false, lfe_mode: "off", lfe_send: 0.0, lfe_gain_db: 0.0, decorrelate: 0.0 },
    enhance: { sub_gain_db: 1.5, mid_gain_db: 0.5, unify_hz: 90.0, spread: "bed", punch: 0.2, excite: true, lfe_mode: "add", lfe_send: 0.25, lfe_gain_db: 1.0, decorrelate: 0.0 },
    deep: { sub_gain_db: 1.0, mid_gain_db: 0.5, unify_hz: 90.0, spread: "bed", punch: 0.25, excite: true, lfe_mode: "add", lfe_send: 0.3, lfe_gain_db: 1.0, decorrelate: 0.0 },
    cinema: { sub_gain_db: 1.0, mid_gain_db: 0.0, unify_hz: 80.0, spread: "bed", punch: 0.0, excite: false, lfe_mode: "split", lfe_send: 0.5, lfe_gain_db: 0.0, decorrelate: 0.0 },
  },
  delivery_default: { target_lkfs: -18.0, max_tp_dbtp: -1.0, tolerance_lu: null },
  delivery_targets: {
    "atmos-music": { target_lkfs: -18.0, max_tp_dbtp: -1.0, tolerance_lu: null },
    "netflix-atmos": { target_lkfs: -27.0, max_tp_dbtp: -2.0, tolerance_lu: 2.0 },
    "ebu-r128": { target_lkfs: -23.0, max_tp_dbtp: -1.0, tolerance_lu: 0.5 },
    "atsc-a85": { target_lkfs: -24.0, max_tp_dbtp: -2.0, tolerance_lu: 2.0 },
    "streaming-stereo": { target_lkfs: -14.0, max_tp_dbtp: -1.0, tolerance_lu: null },
    "apple-music": { target_lkfs: -16.0, max_tp_dbtp: -1.0, tolerance_lu: null },
  },
  bass_sub_cutoff_hz: 80.0,
  bass_mid_cutoff_hz: 200.0,
  bass_excite_blend: 0.15,
  bass_excite_drive: 3.0,
  bass_lf_spreads: {
    front: ["FL", "FR"],
    bed: ["FL", "FR", "C", "SL", "SR", "BL", "BR"],
    all: ["FL", "FR", "C", "SL", "SR", "BL", "BR", "TFL", "TFR", "TBL", "TBR"],
  },
  bass_punch_fast_ms: 10.0,
  bass_punch_slow_ms: 120.0,
  bass_punch_max_db: 6.0,
    bass_decorr_low_hz: 100.0,
    bass_decorr_high_hz: 300.0,
    bass_decorr_sections: 32,
    bass_decorr_max_delay_ms: 30.0,
    bass_decorr_fast_ms: 30.0,
    bass_decorr_slow_ms: 300.0,
  binaural_loudness_max_gain_db: 6.0,
  crosstalk_loudness_max_gain_db: 6.0,
  voicing_params: {
    flat: { ...neutral },
    studio: { ...neutral },
    listening: {
      crossfeed_amount: 0.1,
      crossfeed_cutoff_hz: 700,
      bass_shelf_hz: 100,
      bass_shelf_gain_db: 1.0,
      air_shelf_hz: 10000,
      air_shelf_gain_db: 4.0,
      presence_hz: 3000,
      presence_gain_db: 2.0,
      presence_q: 0.9,
      stereo_widen: 0.15,
      loudness_target_lkfs: null,
    },
  },
  transaural_voicing_params: {
    stereo: { ...neutral },
    smart_speaker: { ...neutral, bass_shelf_hz: 150, bass_shelf_gain_db: 1.5, stereo_widen: 0.2 },
    car: { ...neutral, bass_shelf_hz: 120, bass_shelf_gain_db: 2.5, presence_hz: 2500, presence_gain_db: 1.0, stereo_widen: 0.1 },
    laptop: { ...neutral, bass_shelf_hz: 160, bass_shelf_gain_db: 2.0, presence_hz: 3000, presence_gain_db: 1.0, stereo_widen: 0.25 },
    phone: { ...neutral, bass_shelf_hz: 180, bass_shelf_gain_db: 3.0, presence_hz: 3000, presence_gain_db: 1.5, stereo_widen: 0.3 },
  },
  eq_fir_assets: {
    "spatial-transparent": "master_spatial-transparent",
    "spatial-air": "master_spatial-air",
    "spatial-warm": "master_spatial-warm",
    "spatial-present": "master_spatial-present",
    "atmos-streaming": "master_atmos-streaming",
  },
  stem_eq_fir_assets: {
    "vocal-presence": "stem_vocal-presence",
    "vocal-warmth": "stem_vocal-warmth",
    "bass-warmth": "stem_bass-warmth",
    "bass-cut": "stem_bass-cut",
    "drums-punch": "stem_drums-punch",
    "other-air": "stem_other-air",
    flat: "stem_flat",
  },
  stem_eq_settings: {
    flat: { preset: "flat", bypass: false, highpass: { enabled: false, freq_hz: 20 }, low_shelf: { enabled: false, freq_hz: 120, gain_db: 0, q: .707 }, bell_1: { enabled: false, freq_hz: 1000, gain_db: 0, q: 1 }, bell_2: { enabled: false, freq_hz: 4000, gain_db: 0, q: 1 }, high_shelf: { enabled: false, freq_hz: 8000, gain_db: 0, q: .707 }, lowpass: { enabled: false, freq_hz: 20000 }, mix: 100 },
  },
  decode_filter_set: {
    flat: "flat_o3_decode",
    studio: "studio_o3_decode",
    listening: "listening_o3_decode",
  },
  xtc_filter_set: {
    stereo: "stereo_xtc",
    smart_speaker: "smart_speaker_xtc",
    car: "car_xtc",
    laptop: "laptop_xtc",
    phone: "phone_xtc",
  },
};

export const TEST_ENGINE_CONSTANTS = resolveEngineConstants(TEST_SERVED_CONSTANTS);
